### ISSUE TITLE
node modules don't install on node 13+

### ISSUE THREAD

**Issue by piprett** [tmpim/shitty.dl#46]
The last node version I was able to install packages on was node 12.

**Comment by Lemmmy** [comment]
no logs?

**Comment by piprett** [comment]
<details><summary>Logs</summary>
<p>

```
711 verbose stack Error: command failed
711 verbose stack     at ChildProcess.<anonymous> (/home/erlend/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
711 verbose stack     at ChildProcess.emit (node:events:513:28)
711 verbose stack     at maybeClose (node:internal/child_process:1100:16)
711 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
712 verbose pkgid oniguruma@6.2.1
713 verbose cwd /home/erlend/Coding/shitty.dl
714 verbose Linux 6.1.0-18-amd64
715 verbose node v16.20.2
716 verbose npm  v8.19.4
717 error code 1
718 error path /home/erlend/Coding/shitty.dl/node_modules/oniguruma
719 error command failed
720 error command sh -c -- node-gyp rebuild
721 error make: Entering directory '/home/erlend/Coding/shitty.dl/node_modules/oniguruma/build'
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/st.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
721 error   CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
721 error   AR(target) Release/obj.target/oniguruma.a
721 error   COPY Release/oniguruma.a
721 error   CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
721 error make: Leaving directory '/home/erlend/Coding/shitty.dl/node_modules/oniguruma/build'
722 error gyp info it worked if it ends with ok
722 error gyp info using node-gyp@9.1.0
722 error gyp info using node@16.20.2 | linux | x64
722 error gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
722 error gyp info spawn /usr/bin/python3
722 error gyp info spawn args [
722 error gyp info spawn args   '/home/erlend/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
722 error gyp info spawn args   'binding.gyp',
722 error gyp info spawn args   '-f',
722 error gyp info spawn args   'make',
722 error gyp info spawn args   '-I',
722 error gyp info spawn args   '/home/erlend/Coding/shitty.dl/node_modules/oniguruma/build/config.gypi',
722 error gyp info spawn args   '-I',
722 error gyp info spawn args   '/home/erlend/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
722 error gyp info spawn args   '-I',
722 error gyp info spawn args   '/home/erlend/.cache/node-gyp/16.20.2/include/node/common.gypi',
722 error gyp info spawn args   '-Dlibrary=shared_library',
722 error gyp info spawn args   '-Dvisibility=default',
722 error gyp info spawn args   '-Dnode_root_dir=/home/erlend/.cache/node-gyp/16.20.2',
722 error gyp info spawn args   '-Dnode_gyp_dir=/home/erlend/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp',
722 error gyp info spawn args   '-Dnode_lib_file=/home/erlend/.cache/node-gyp/16.20.2/<(target_arch)/node.lib',
722 error gyp info spawn args   '-Dmodule_root_dir=/home/erlend/Coding/shitty.dl/node_modules/oniguruma',
722 error gyp info spawn args   '-Dnode_engine=v8',
722 error gyp info spawn args   '--depth=.',
722 error gyp info spawn args   '--no-parallel',
722 error gyp info spawn args   '--generator-output',
722 error gyp info spawn args   'build',
722 error gyp info spawn args   '-Goutput_dir=.'
722 error gyp info spawn args ]
722 error gyp info spawn make
722 error gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
722 error In file included from ../../nan/nan_converters.h:67,
722 error                  from ../../nan/nan.h:202,
722 error                  from ../src/onig-result.h:4,
722 error                  from ../src/onig-result.cc:1:
722 error ../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ToFactoryBase<v8::Boolean>::return_t Nan::imp::ToFactory<v8::Boolean>::convert(v8::Local<v8::Value>)’:
722 error ../../nan/nan_converters_43_inl.h:18:49: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
722 error    18 |       val->To ## TYPE(isolate->GetCurrentContext())                            \
722 error       |                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
722 error       |                                                 |
722 error       |                                                 v8::Local<v8::Context>
722 error ../../nan/nan_converters_43_inl.h:22:1: note: in expansion of macro ‘X’
722 error    22 | X(Boolean)
722 error       | ^
722 error In file included from /home/erlend/.cache/node-gyp/16.20.2/include/node/node.h:73,
722 error                  from ../../nan/nan.h:51:
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3086:37: note:   initializing argument 1 of ‘v8::Local<v8::Boolean> v8::Value::ToBoolean(v8::Isolate*) const’
722 error  3086 |   Local<Boolean> ToBoolean(Isolate* isolate) const;
722 error       |                            ~~~~~~~~~^~~~~~~
722 error ../../nan/nan_converters_43_inl.h: In static member function ‘static Nan::imp::ValueFactoryBase<bool>::return_t Nan::imp::ToFactory<bool>::convert(v8::Local<v8::Value>)’:
722 error ../../nan/nan_converters_43_inl.h:37:55: error: cannot convert ‘v8::Local<v8::Context>’ to ‘v8::Isolate*’
722 error    37 |   return val->NAME ## Value(isolate->GetCurrentContext());                     \
722 error       |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
722 error       |                                                       |
722 error       |                                                       v8::Local<v8::Context>
722 error ../../nan/nan_converters_43_inl.h:40:1: note: in expansion of macro ‘X’
722 error    40 | X(bool, Boolean)
722 error       | ^
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3096:30: note:   initializing argument 1 of ‘bool v8::Value::BooleanValue(v8::Isolate*) const’
722 error  3096 |   bool BooleanValue(Isolate* isolate) const;
722 error       |                     ~~~~~~~~~^~~~~~~
722 error In file included from ../../nan/nan_new.h:189,
722 error                  from ../../nan/nan.h:203:
722 error ../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::Function>::return_t Nan::imp::Factory<v8::Function>::New(Nan::FunctionCallback, v8::Local<v8::Value>)’:
722 error ../../nan/nan_implementation_12_inl.h:103:42: error: cannot convert ‘v8::Isolate*’ to ‘v8::Local<v8::Context>’
722 error   103 |   return scope.Escape(v8::Function::New( isolate
722 error       |                                          ^~~~~~~
722 error       |                                          |
722 error       |                                          v8::Isolate*
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4754:22: note:   initializing argument 1 of ‘static v8::MaybeLocal<v8::Function> v8::Function::New(v8::Local<v8::Context>, v8::FunctionCallback, v8::Local<v8::Value>, int, v8::ConstructorBehavior, v8::SideEffectType)’
722 error  4754 |       Local<Context> context, FunctionCallback callback,
722 error       |       ~~~~~~~~~~~~~~~^~~~~~~
722 error ../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
722 error ../../nan/nan_implementation_12_inl.h:337:31: error: no matching function for call to ‘v8::StringObject::New(v8::Local<v8::String>&)’
722 error   337 |   return v8::StringObject::New(value).As<v8::StringObject>();
722 error       |          ~~~~~~~~~~~~~~~~~~~~~^~~~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:6196:23: note: candidate: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Isolate*, v8::Local<v8::String>)’
722 error  6196 |   static Local<Value> New(Isolate* isolate, Local<String> value);
722 error       |                       ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:6196:23: note:   candidate expects 2 arguments, 1 provided
722 error ../../nan/nan_implementation_12_inl.h:337:58: error: expected primary-expression before ‘>’ token
722 error   337 |   return v8::StringObject::New(value).As<v8::StringObject>();
722 error       |                                                          ^
722 error ../../nan/nan_implementation_12_inl.h:337:60: error: expected primary-expression before ‘)’ token
722 error   337 |   return v8::StringObject::New(value).As<v8::StringObject>();
722 error       |                                                            ^
722 error ../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
722 error ../../nan/nan.h:1034:52: error: no matching function for call to ‘v8::Value::ToString()’
722 error  1034 |       v8::Local<v8::String> string = from->ToString();
722 error       |                                      ~~~~~~~~~~~~~~^~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3048:44: note: candidate: ‘v8::MaybeLocal<v8::String> v8::Value::ToString(v8::Local<v8::Context>) const’
722 error  3048 |   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
722 error       |                                            ^~~~~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3048:44: note:   candidate expects 1 argument, 0 provided
722 error ../../nan/nan.h:1044:37: error: cannot convert ‘char*’ to ‘v8::Isolate*’
722 error  1044 |         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
722 error       |                                     ^~~~
722 error       |                                     |
722 error       |                                     char*
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3277:26: note:   initializing argument 1 of ‘int v8::String::WriteUtf8(v8::Isolate*, char*, int, int*, int) const’
722 error  3277 |   int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
722 error       |                 ~~~~~~~~~^~~~~~~
722 error ../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const char*, const v8::Local<v8::Value>&)’:
722 error ../../nan/nan.h:1818:31: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, const v8::Local<v8::Value>&)’
722 error  1818 |     New(persistentHandle)->Set(New(key).ToLocalChecked(), value);
722 error       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
722 error  3961 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
722 error       |                                     ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3961:37: note:   candidate expects 3 arguments, 2 provided
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
722 error  3964 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
722 error       |                                     ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3964:37: note:   candidate expects 3 arguments, 2 provided
722 error ../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’:
722 error ../../nan/nan.h:1824:31: error: no matching function for call to ‘v8::Object::Set(const v8::Local<v8::String>&, const v8::Local<v8::Value>&)’
722 error  1824 |     New(persistentHandle)->Set(key, value);
722 error       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
722 error  3961 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
722 error       |                                     ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3961:37: note:   candidate expects 3 arguments, 2 provided
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
722 error  3964 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
722 error       |                                     ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3964:37: note:   candidate expects 3 arguments, 2 provided
722 error ../../nan/nan.h: In member function ‘void Nan::AsyncWorker::SaveToPersistent(uint32_t, const v8::Local<v8::Value>&)’:
722 error ../../nan/nan.h:1830:31: error: no matching function for call to ‘v8::Object::Set(uint32_t&, const v8::Local<v8::Value>&)’
722 error  1830 |     New(persistentHandle)->Set(index, value);
722 error       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3961:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
722 error  3961 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
722 error       |                                     ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3961:37: note:   candidate expects 3 arguments, 2 provided
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3964:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
722 error  3964 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
722 error       |                                     ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:3964:37: note:   candidate expects 3 arguments, 2 provided
722 error ../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const char*) const’:
722 error ../../nan/nan.h:1836:35: error: no matching function for call to ‘v8::Object::Get(v8::Local<v8::String>)’
722 error  1836 |         New(persistentHandle)->Get(New(key).ToLocalChecked()));
722 error       |         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4007:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
722 error  4007 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
722 error       |                                           ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4007:43: note:   candidate expects 2 arguments, 1 provided
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4010:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
722 error  4010 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
722 error       |                                           ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4010:43: note:   candidate expects 2 arguments, 1 provided
722 error ../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(const v8::Local<v8::String>&) const’:
722 error ../../nan/nan.h:1842:51: error: no matching function for call to ‘v8::Object::Get(const v8::Local<v8::String>&)’
722 error  1842 |     return scope.Escape(New(persistentHandle)->Get(key));
722 error       |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4007:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
722 error  4007 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
722 error       |                                           ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4007:43: note:   candidate expects 2 arguments, 1 provided
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4010:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
722 error  4010 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
722 error       |                                           ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4010:43: note:   candidate expects 2 arguments, 1 provided
722 error ../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::AsyncWorker::GetFromPersistent(uint32_t) const’:
722 error ../../nan/nan.h:1847:51: error: no matching function for call to ‘v8::Object::Get(uint32_t&)’
722 error  1847 |     return scope.Escape(New(persistentHandle)->Get(index));
722 error       |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4007:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, v8::Local<v8::Value>)’
722 error  4007 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
722 error       |                                           ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4007:43: note:   candidate expects 2 arguments, 1 provided
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4010:43: note: candidate: ‘v8::MaybeLocal<v8::Value> v8::Object::Get(v8::Local<v8::Context>, uint32_t)’
722 error  4010 |   V8_WARN_UNUSED_RESULT MaybeLocal<Value> Get(Local<Context> context,
722 error       |                                           ^~~
722 error /home/erlend/.cache/node-gyp/16.20.2/include/node/v8.h:4010:43: note:   candidate expects 2 arguments, 1 provided
722 error ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(AsyncWorker*)’:
722 error ../../nan/nan.h:2167:7: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
722 error  2167 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
722 error       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
722 error In file included from /usr/include/c++/12/cassert:44,
722 error                  from /home/erlend/.cache/node-gyp/16.20.2/include/node/node_object_wrap.h:26,
722 error                  from ../../nan/nan.h:53:
722 error ../../nan/nan_object_wrap.h: In destructor ‘virtual Nan::ObjectWrap::~ObjectWrap()’:
722 error ../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
722 error    24 |     assert(persistent().IsNearDeath());
722 error       |                         ^~~~~~~~~~~
722 error In file included from ../../nan/nan.h:2657:
722 error ../../nan/nan_object_wrap.h: In member function ‘void Nan::ObjectWrap::MakeWeak()’:
722 error ../../nan/nan_object_wrap.h:67:18: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘MarkIndependent’
722 error    67 |     persistent().MarkIndependent();
722 error       |                  ^~~~~~~~~~~~~~~
722 error ../../nan/nan_object_wrap.h: In static member function ‘static void Nan::ObjectWrap::WeakCallback(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’:
722 error ../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
722 error   124 |     assert(wrap->handle_.IsNearDeath());
722 error       |                          ^~~~~~~~~~~
722 error make: *** [onig_scanner.target.mk:127: Release/obj.target/onig_scanner/src/onig-result.o] Error 1
722 error gyp ERR! build error 
722 error gyp ERR! stack Error: `make` failed with exit code: 2
722 error gyp ERR! stack     at ChildProcess.onExit (/home/erlend/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
722 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
722 error gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
722 error gyp ERR! System Linux 6.1.0-18-amd64
722 error gyp ERR! command "/home/erlend/.nvm/versions/node/v16.20.2/bin/node" "/home/erlend/.nvm/versions/node/v16.20.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
722 error gyp ERR! cwd /home/erlend/Coding/shitty.dl/node_modules/oniguruma
722 error gyp ERR! node -v v16.20.2
722 error gyp ERR! node-gyp -v v9.1.0
722 error gyp ERR! not ok
```

</p>
</details> 

Full log file: https://p.sc3.io/XgVKJ7UKyF
In this case node 16
